version: '2'
services:
  http_header:
    image: 'ryu310/http-header-docker-compose:httpd-2.4.29-02'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'http_header_config:/usr/local/apache2/conf'
      - 'http_header_data:/usr/local/apache2/htdocs'
    ports:
      - 80:80
    # Enable to restart container (It is useful for Docker for Windows)
    #restart: always
  wiki:
    image: 'ryu310/pukiwiki-plus:php-7.2.2-apache-1.4.7-02'
    volumes:
      - 'wiki_data:/var/www/html/wiki'
      - 'apache_config:/etc/apache2'
      - 'apachegui_db:/opt/ApacheGUI/tomcat/db'
      - 'php_config:/usr/local/etc/php'
    environment:
      - SUBDIR=/wiki
    # Enable to restart container (It is useful for Docker for Windows)
    #restart: always
volumes:
  http_header_config:
  http_header_data:
  wiki_data:
  apache_config:
  apachegui_db:
  php_config:

